### ISSUE TITLE
libcudart.so.10.2 & libcufft.so.10 not found, undefined reference to cuda dynamic libs

### ISSUE THREAD

**Issue by dirksavage88** [NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline#18]
I am on Jetpack 4.6.1, Jetson Nano, and using the issac_ros_* release-ea2 branches for isaac_ros_common, isaac_ros_image_pipeline, & isaac_ros_apriltag. I have run "git lfs pull" in each of the repo folders. 

 Container successfully builds. I see libcudart and libcufft in /usr/local/cuda-10.2/lib64.

When I run colcon build within my container workspace, I get this error when building isaac_ros_image_proc:

**/usr/bin/ld: warning: libcudart.so.10.2, needed by /opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcufft.so.10, needed by /opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15, not found (try using -rpath or -rpath-link)
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpyToArray@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cufftExecC2R@libcufft.so.10'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEGLStreamConsumerReleaseFrame@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEGLStreamProducerReturnFrame@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cufftMakePlanMany@libcufft.so.10'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `__cudaRegisterFunction@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `__cudaUnregisterFatBinary@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpy2DAsync@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMallocManaged@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpy2DToArrayAsync@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaCreateTextureObject@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaDestroyTextureObject@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemset2D@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEventCreateWithFlags@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cufftCreate@libcufft.so.10'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cufftSetStream@libcufft.so.10'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaGraphicsUnregisterResource@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaGetMipmappedArrayLevel@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaGetErrorName@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaGetErrorString@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaCreateSurfaceObject@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `__cudaPopCallConfiguration@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `__cudaRegisterVar@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaGetDeviceProperties@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `__cudaRegisterFatBinary@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaArrayGetInfo@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpyToArrayAsync@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaFreeHost@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaFree@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaStreamDestroy@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaGetDevice@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaStreamWaitEvent@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEventDestroy@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEventSynchronize@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEGLStreamProducerDisconnect@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemset@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEGLStreamProducerPresentFrame@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cufftExecC2C@libcufft.so.10'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEventCreate@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpyFromArray@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaDeviceGetAttribute@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaGetDeviceCount@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaStreamAttachMemAsync@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEventQuery@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaStreamCreate@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEventElapsedTime@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEventRecord@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaFreeArray@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaDeviceSynchronize@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpy2D@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaDestroySurfaceObject@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaGetDeviceFlags@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaGraphicsEGLRegisterImage@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `__cudaRegisterFatBinaryEnd@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEGLStreamConsumerAcquireFrame@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaHostUnregister@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaLaunchKernel@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEGLStreamConsumerConnect@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cufftGetSizeMany@libcufft.so.10'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEGLStreamConsumerDisconnect@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaStreamAddCallback@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaHostGetDevicePointer@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMallocArray@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemset2DAsync@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpy2DFromArrayAsync@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cufftSetAutoAllocation@libcufft.so.10'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpyArrayToArray@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpy2DFromArray@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaGraphicsResourceGetMappedEglFrame@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpyFromArrayAsync@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemsetAsync@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaHostAlloc@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpy2DArrayToArray@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpyFromSymbol@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cufftDestroy@libcufft.so.10'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpy@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaPointerGetAttributes@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMallocPitch@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMalloc@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaEGLStreamProducerConnect@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaStreamSynchronize@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaHostRegister@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cufftSetWorkArea@libcufft.so.10'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaCreateChannelDesc@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `__cudaPushCallConfiguration@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpyAsync@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaGetLastError@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cudaMemcpy2DToArray@libcudart.so.10.2'
/opt/nvidia/vpi1/lib64/libnvvpi.so.1.1.15: undefined reference to `cufftExecR2C@libcufft.so.10'
collect2: error: ld returned 1 exit status
make[2]: *** [isaac_ros_image_proc] Error 1
make[1]: *** [CMakeFiles/isaac_ros_image_proc.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< isaac_ros_image_proc [2.82s, exited with code 2]
Aborted  <<< isaac_ros_stereo_image_proc [4.24s]**                              

 Looks like vpi is not able to link to these cuda libs? isaac_ros_common builds correctly

**Comment by hemalshahNV** [comment]
Could you check that the CUDA 10.2 libs are available where  LD_LIBRARY_PATH: [Dockerfile.aarch64.base](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/b5261b2d7cd3a1e9dfb857ad5a0664766dbd385c/docker/Dockerfile.aarch64.base#L116) for EA2 

```
ENV LD_LIBRARY_PATH="/usr/local/cuda-10.2/targets/aarch64-linux/lib:${LD_LIBRARY_PATH}"
```

Could you try with EA3 instead which was the last ROS2 Foxy on JP 4.6.1 Isaac ROS release? We are not able to support any previous Early Access releases.

**Comment by dirksavage88** [comment]
@hemalshahNV will EA3 work with the L4T r32.6.1 base image? I see that EA2 is the latest branch with that base image called out in the Docker.aarch64.base
